# Generated by Django 2.0.5 on 2018-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
